// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_prepare_alignment_matrix
CharacterMatrix rcpp_prepare_alignment_matrix(CharacterMatrix ref);
RcppExport SEXP AlikeAlignmentAligner_rcpp_prepare_alignment_matrix(SEXP refSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterMatrix >::type ref(refSEXP);
    __result = Rcpp::wrap(rcpp_prepare_alignment_matrix(ref));
    return __result;
END_RCPP
}
// rcpp_align
List rcpp_align(CharacterMatrix ref, CharacterMatrix com);
RcppExport SEXP AlikeAlignmentAligner_rcpp_align(SEXP refSEXP, SEXP comSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterMatrix >::type ref(refSEXP);
    Rcpp::traits::input_parameter< CharacterMatrix >::type com(comSEXP);
    __result = Rcpp::wrap(rcpp_align(ref, com));
    return __result;
END_RCPP
}
