# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_prepare_alignment_matrix <- function(ref) {
    .Call('_AlignStat_rcpp_prepare_alignment_matrix', PACKAGE = 'AlignStat', ref)
}

rcpp_align <- function(ref, com) {
    .Call('_AlignStat_rcpp_align', PACKAGE = 'AlignStat', ref, com)
}

