# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_align <- function(ref, aln) {
    .Call('AlikeAlignmentAligner_rcpp_align', PACKAGE = 'AlikeAlignmentAligner', ref, aln)
}

